// Code generated by MockGen. DO NOT EDIT.
// Source: ./db_provider.go

// Package txmng is a generated GoMock package.
package txmng

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBProvider is a mock of DBProvider interface.
type MockDBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDBProviderMockRecorder
}

// MockDBProviderMockRecorder is the mock recorder for MockDBProvider.
type MockDBProviderMockRecorder struct {
	mock *MockDBProvider
}

// NewMockDBProvider creates a new mock instance.
func NewMockDBProvider(ctrl *gomock.Controller) *MockDBProvider {
	mock := &MockDBProvider{ctrl: ctrl}
	mock.recorder = &MockDBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBProvider) EXPECT() *MockDBProviderMockRecorder {
	return m.recorder
}

// Raw mocks base method.
func (m *MockDBProvider) Raw() DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Raw")
	ret0, _ := ret[0].(DB)
	return ret0
}

// Raw indicates an expected call of Raw.
func (mr *MockDBProviderMockRecorder) Raw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Raw", reflect.TypeOf((*MockDBProvider)(nil).Raw))
}

// Tx mocks base method.
func (m *MockDBProvider) Tx(opts Opts) (DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx", opts)
	ret0, _ := ret[0].(DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tx indicates an expected call of Tx.
func (mr *MockDBProviderMockRecorder) Tx(opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockDBProvider)(nil).Tx), opts)
}
