// Code generated by MockGen. DO NOT EDIT.
// Source: ./db_provider.go
//
// Generated by this command:
//
//	mockgen -source=./db_provider.go -destination=./db_provider_mock.go -package txmng
//

// Package txmng is a generated GoMock package.
package txmng

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTx is a mock of Tx interface.
type MockTx[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder[T]
	isgomock struct{}
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder[T any] struct {
	mock *MockTx[T]
}

// NewMockTx creates a new mock instance.
func NewMockTx[T any](ctrl *gomock.Controller) *MockTx[T] {
	mock := &MockTx[T]{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx[T]) EXPECT() *MockTxMockRecorder[T] {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx[T]) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder[T]) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx[T])(nil).Commit), ctx)
}

// GetDB mocks base method.
func (m *MockTx[T]) GetDB() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(T)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockTxMockRecorder[T]) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockTx[T])(nil).GetDB))
}

// Rollback mocks base method.
func (m *MockTx[T]) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder[T]) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx[T])(nil).Rollback), ctx)
}

// MockDBProvider is a mock of DBProvider interface.
type MockDBProvider[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDBProviderMockRecorder[T]
	isgomock struct{}
}

// MockDBProviderMockRecorder is the mock recorder for MockDBProvider.
type MockDBProviderMockRecorder[T any] struct {
	mock *MockDBProvider[T]
}

// NewMockDBProvider creates a new mock instance.
func NewMockDBProvider[T any](ctrl *gomock.Controller) *MockDBProvider[T] {
	mock := &MockDBProvider[T]{ctrl: ctrl}
	mock.recorder = &MockDBProviderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBProvider[T]) EXPECT() *MockDBProviderMockRecorder[T] {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDBProvider[T]) BeginTx(opts TxOpts) (Tx[T], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", opts)
	ret0, _ := ret[0].(Tx[T])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDBProviderMockRecorder[T]) BeginTx(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDBProvider[T])(nil).BeginTx), opts)
}

// GetDB mocks base method.
func (m *MockDBProvider[T]) GetDB(opts NoTxOpts) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", opts)
	ret0, _ := ret[0].(T)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockDBProviderMockRecorder[T]) GetDB(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockDBProvider[T])(nil).GetDB), opts)
}
