// Code generated by MockGen. DO NOT EDIT.
// Source: ./txmng.go
//
// Generated by this command:
//
//	mockgen -source=./txmng.go -destination=./txmng_mock.go -package txmng
//

// Package txmng is a generated GoMock package.
package txmng

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTxManager) RunTx(opts Opts, f func(Context) (Scanner, error)) (Scanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", opts, f)
	ret0, _ := ret[0].(Scanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxManagerMockRecorder) WithTx(opts, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxManager)(nil).RunTx), opts, f)
}

// WithoutTx mocks base method.
func (m *MockTxManager) RunNoTx(ctx context.Context, f func(Context) (Scanner, error)) (Scanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithoutTx", ctx, f)
	ret0, _ := ret[0].(Scanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithoutTx indicates an expected call of WithoutTx.
func (mr *MockTxManagerMockRecorder) WithoutTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithoutTx", reflect.TypeOf((*MockTxManager)(nil).RunNoTx), ctx, f)
}

// MockDBManager is a mock of DBManager interface.
type MockDBManager[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDBManagerMockRecorder[T]
	isgomock struct{}
}

// MockDBManagerMockRecorder is the mock recorder for MockDBManager.
type MockDBManagerMockRecorder[T any] struct {
	mock *MockDBManager[T]
}

// NewMockDBManager creates a new mock instance.
func NewMockDBManager[T any](ctrl *gomock.Controller) *MockDBManager[T] {
	mock := &MockDBManager[T]{ctrl: ctrl}
	mock.recorder = &MockDBManagerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBManager[T]) EXPECT() *MockDBManagerMockRecorder[T] {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockDBManager[T]) GetDB(ctx Context) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", ctx)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockDBManagerMockRecorder[T]) GetDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockDBManager[T])(nil).GetDB), ctx)
}
